### ISSUE TITLE
SQL error upon Worldserver Run

### ISSUE THREAD

**Issue by LunarEngineer** [JustinChristensen/trinitycore-dockerfile#4]
**System Details**
Docker Version:  Docker version 19.03.12, build 48a66213fe
Operation System: Ubuntu (uname -a: Linux gaia 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)
Any other details relevant to the problem.

First, I understand you're not maintaining this and I won't be hurt if you don't respond to this.

I ran your workflow, essentially vanilla but changing a couple of variable names to match variable names in other parts of my already existent process.

I took Nicola Worthington's work where she had a more extensible build script and folded that into a prebuild shell script, just making sure all the hooks and parts and pieces worked, that fires before the make script.

Everything seems fine:
* The db container works and I can run SQL commands.
* The auth server (after I modified the create SQL to reflect current Trinity DB standards) worked and is up and running.
* The world server dies. It finishes unpacking just fine and creates (I'm assuming) all the proper structure in the volume created for the stack but when the world server starts it appears to be running SQL internal to the Trinity core that's causing a crash when it's trying to update a wander_distance field in world.creature that doesn't exist.

I'm assuming this is all in the Trinity codebase but I'm opening the issue in the off chance that you experienced this while you were testing.

**Logs**
```
Extracting client data...,
dbc and maps already extracted, skipping,
vmaps already extracted, skipping,
mmaps already extracted, skipping,
Checking database connection...,
ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115),
ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115),
ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115),


10.5.4-MariaDB-1:10.5.4+maria~focal

Creating databases...

ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'trinity'@'%'

Creating and populating tables for characters...

Running updates for characters...

Creating and populating tables for world...

Running updates for world...

Setting database configuration from env...

**In mysql_stmt_prepare() id: 19, sql: "UPDATE creature SET wander_distance = ?, MovementType = ? WHERE guid = ?"**

Unknown column 'wander_distance' in 'field list'

In mysql_stmt_prepare() id: 61, sql: "INSERT INTO creature (guid, id , map, spawnMask, phaseMask, modelid, equipment_id, position_x, position_y, position_z, orientation, spawntimesecs, wander_distance, currentwaypoint, curhealth, curmana, MovementType, npcflag, unit_flags, dynamicflags) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"

Unknown column 'wander_distance' in 'field list'

Could not prepare statements of the World database, see log for details.

TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

<Ctrl-C> to stop.
..pictures..

Using configuration file /usr/local/etc/worldserver.conf.


Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)


Using Boost version: 1.67.0


Automatic database updates are disabled for all databases!
```

**Comment by JustinChristensen** [comment]
The issue is that they've continued to modify the SQL scripts that create the database tables on the 3.3.5 branch since I 
created these dockerfiles. 

For example, this commit changes the column names and causes one of the SQL scripts I've got in this repository to fail:
https://github.com/TrinityCore/TrinityCore/commit/01d098830a64622262226f7915f872e1cfb301f6#diff-d5efd50ad7283351464895564eff9116

From a philosophical standpoint, I tried to author these docker scripts in such a way that the user would have to opt-in to code and database updates, and to that end I accidentally introduced a bug when I documented that the user should specify "3.3.5" for TRINITYCORE_VERSION.

In fact, that pulls down the latest code on the 3.3.5 branch, when what I meant to do was pin this to a specific and known working version of the code and database schema.

To that end I've updated the README. 

As you've surmised, there have been changes since the specific commit I tested this against, and you'll need to track down which scripts need updating.

Let me know if you have further questions, and if not, please close this.

**Comment by JustinChristensen** [comment]
Oh, one more quick note... 

As of right now the expectation from the maintainers of TrinityCore is that the user will pull down the TrinityCore repository and that either branch 3.3.5 or master will be in a compilable and functioning state. Without a formal release process this is extremely hard to guarantee (even if the maintainers fancy themselves as the kind of programmers who don't make mistakes).

A better practice would be for them to periodically test and tag specific commits with a release version number, and to document that users should be working off of those commits.

The reason I'm bringing this is up is that, in addition to the changes introduced between the version of the code this was tested with, you also may run into a situation where the latest commit on one of those two branches just isn't in a functioning state.

**Comment by LunarEngineer** [comment]
Thanks, it's appreciated!
